services:
  app:
    build: .
    container_name: cuent_ai_core
    ports:
      - "${PORT}:${PORT}"
    env_file:
      - .env
    environment:
      - PORT=${PORT}
      - DATABASE_URL=${DATABASE_URL}
      - GOFLAGS=-buildvcs=false
    volumes:
      - .:/app
      - /go/pkg/mod
      - /app/tmp
